#!/bin/bash

image_name=$1
docker_user=${DOCKER_USER}
docker_password=${DOCKER_PASSWORD}
branch=${CIRCLE_BRANCH}
revision=${CIRCLE_SHA1}

./check-if-changed ${image_name}
retVal=$?
if [ $retVal == 0 ]; then
  echo "Building ${image_name}"
  docker build --build-arg TAG=${branch} -t ${image_name} ${image_name}

  docker login --username ${docker_user} --password ${docker_password}
  for tag in "$branch" "$revision"; do
    echo "Deploying image with tag: ${tag}"
    docker tag ${image_name} ataber/${image_name}:${tag}
    docker push ataber/${image_name}:$tag}
  done
else
  echo "No changes for image ${image_name}"
  exit 0
fi
