#!/bin/bash

mkdir -p branch_cache
directory_name=$1
if [[ $(git diff --name-only HEAD..HEAD^ | grep ${directory_name}) ]]; then
  touch branch_cache/${directory_name}
  exit 0
else
  first_line=$(head -n 2 ${directory_name}/Dockerfile)
  for file in ./branch_cache/* ; do
    if [[ -f "$file" ]]; then
      p=${file:15}

      if [[ $first_line == *"$p"* ]]; then
        touch branch_cache/${directory_name}
        exit 0
      fi
    fi
  done

  exit 1
fi
