#!/bin/bash

mkdir -p branch_cache
directory_name=$1
change_dirs=$(git diff --name-only HEAD..HEAD^)

changed_images=()
for file in $change_dirs
do
  if [[ $file == *"/Dockerfile"* ]]; then
    changed_image=${file%/*}
    changed_images+=(${changed_image})
  fi
done

files=($(ls -d */Dockerfile))
while true; do
  still_propagating=false
  for f in "${files[@]}"
  do
    downstream_image=${f%/*}
    if [[ ! " ${changed_images[@]} " =~ " ${downstream_image} " ]]; then
      for i in "${changed_images[@]}"
      do
        if $(grep -q ${i} "$f")
        then
          changed_images+=($downstream_image)
          still_propagating=true
        fi
      done
    fi
  done

  if [ "$still_propagating" = false ] ; then
    break
  fi
done

if [[ " ${changed_images[@]} " =~ " ${directory_name} " ]]; then
  exit 0
else
  exit 1
fi
