#!/bin/bash

config_file=.circleci/config.yml
rm -f ${config_file}
touch ${config_file}
echo "version: 2.1

executors:
  compiler:
    docker:
      - image: docker:17.06.0-ce-git
    working_directory: ~/repo

jobs:" >> ${config_file}

for file in ./* ; do
  if [[ -d "$file" ]]; then
    directory_name=${file:2}
    echo "  ${directory_name}:
    executor: compiler
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - attach_workspace:
          at: /root/repo/
      - run:
          name: Build + deploy image
          command: ./build-and-deploy-image ${directory_name}
          no_output_timeout: "30m"
      - persist_to_workspace:
          root: /root/repo
          paths:
            - branch_cache
" >> ${config_file}
  fi;
done

echo "workflows:
  version: 2
  build-images:
    jobs:" >> ${config_file}

for file in ./* ; do
  if [[ -d "$file" ]]; then
    directory_name=${file:2}
    first_line=$(head -n 2 ${directory_name}/Dockerfile)
    if [[ ${first_line} == *"ataber"* ]]; then
      dependent_image=${first_line:27}

      echo "      - ${directory_name}:
          requires:
            - ${dependent_image%?????}" >> ${config_file}
    else
      echo "      - ${directory_name}" >> ${config_file}
    fi
  fi;
done
